learning/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student-dashboard/',include('studymaterial.urls')),
    path('',include('management.urls')),
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

management/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView,LogoutView
app_name = 'management'
urlpatterns = [
    path('',views.home_view,name=''),
    path('<int:subect_id>',views.detail_page,name='detail'),
    path('adminclick', views.adminclick_view),
    path('teacherclick', views.teacherclick_view),
    path('studentclick', views.studentclick_view),
    path('adminsignup', views.admin_signup_view),
    path('studentsignup', views.student_signup_view,name='studentsignup'),
    path('teachersignup', views.teacher_signup_view),
    path('adminlogin', LoginView.as_view(template_name='management/adminlogin.html')),
    path('studentlogin', LoginView.as_view(template_name='management/studentlogin.html')),
    path('teacherlogin', LoginView.as_view(template_name='management/teacherlogin.html')),

    path('afterlogin', views.afterlogin_view,name='afterlogin'),
    path('logout', LogoutView.as_view(template_name='management/index.html'),name='logout'),

    path('admin-dashboard', views.admin_dashboard_view,name='admin-dashboard'),
    path('admin-teacher', views.admin_teacher_view,name='admin-teacher'),
    path('admin-add-teacher', views.admin_add_teacher_view,name='admin-add-teacher'),
    path('admin-view-teacher', views.admin_view_teacher_view,name='admin-view-teacher'),
    path('admin-approve-teacher', views.admin_approve_teacher_view,name='admin-approve-teacher'),
    path('approve-teacher/<int:pk>', views.approve_teacher_view,name='approve-teacher'),
    path('delete-teacher/<int:pk>', views.delete_teacher_view,name='delete-teacher'),
    path('delete-teacher-from-school/<int:pk>', views.delete_teacher_from_school_view,name='delete-teacher-from-school'),
    path('update-teacher/<int:pk>', views.update_teacher_view,name='update-teacher'),
    
    path('admin-student', views.admin_student_view,name='admin-student'),
    path('admin-add-student', views.admin_add_student_view,name='admin-add-student'),
    path('admin-view-student', views.admin_view_student_view,name='admin-view-student'),
    path('delete-student-from-school/<int:pk>', views.delete_student_from_school_view,name='delete-student-from-school'),
    path('delete-student/<int:pk>', views.delete_student_view,name='delete-student'),
    path('update-student/<int:pk>', views.update_student_view,name='update-student'),
    path('admin-approve-student', views.admin_approve_student_view,name='admin-approve-student'),
    path('approve-student/<int:pk>', views.approve_student_view,name='approve-student'),
    path('admin-notice', views.admin_notice_view,name='admin-notice'),
    path('teacher-dashboard', views.teacher_dashboard_view,name='teacher-dashboard'),
    path('teacher-notice', views.teacher_notice_view,name='teacher-notice'),
    path('student-dashboard', views.student_dashboard_view,name='student-dashboard'),
    path('student_joinmeeting', views.student_joinmeeting,name='student_joinmeeing'),
    path('teacher_joinmeeting', views.teacher_joinmeeting,name='teacher_joinmeeing'),
    # path('admin-notice-delete/<int:id>', views.admin_notice_delete,name='admin-notice-delete'),
    
    
]

studymaterial/urls.py
from django.urls import path
from . import views
app_name = 'studymaterial'
urlpatterns = [
    path('youtube',views.youtube, name='youtube'),
    path('books',views.books,name="books"),
    path('dictionary',views.dictionary,name="dictionary"),
    path('wikipedias',views.wikipedias,name="wikipedias"),
    path('joinmeeting',views.joinmeeting,name="joinmeeting"),
    path('googleform',views.googleform,name="googleform"),
]

management/models.py
from django.db import models
from django.contrib.auth.models import User

class Teacher(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    joindate=models.DateField(auto_now_add=True)
    mobile = models.CharField(max_length=40)
    status=models.BooleanField(default=False)
    def __str__(self):
        return self.user.first_name
    @property
    def get_id(self):
        return self.user.id
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name

class Student(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    
    mobile = models.CharField(max_length=40,null=True)
    joindate=models.DateField(auto_now_add=True)
    status=models.BooleanField(default=False)
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_id(self):
        return self.user.id
    def __str__(self):
        return self.user.first_name

class Notice(models.Model):
    date=models.DateField(auto_now=True)
    by=models.CharField(max_length=20,null=True,default='school')
    message=models.CharField(max_length=500)

class Subject(models.Model):
    instructor = models.ForeignKey(User,on_delete=models.CASCADE)
    subect_id=models.CharField(max_length=100,unique=True)
    subject_name=models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    level=models.CharField(max_length=100)
    testlink=models.URLField(max_length=200,null=True,blank=True)
    subject_browser=models.CharField(max_length=2000)
    price=models.IntegerField(default=0)
    subject_image=models.ImageField(upload_to='sub_img/%Y/%m/%d')

    def __str__(self):
        return self.subject_name

management/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

#for admin
class AdminSigupForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password']


#for student related form
class StudentUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password']
class StudentExtraForm(forms.ModelForm):
    class Meta:
        model=models.Student
        fields=['mobile','status']

#for teacher related form
class TeacherUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password']
class TeacherExtraForm(forms.ModelForm):
    class Meta:
        model=models.Teacher
        fields=['mobile','status']

#for notice related form
class NoticeForm(forms.ModelForm):
    class Meta:
        model=models.Notice
        fields='__all__'

management/views.py
from django.core import paginator
from django.http.response import HttpResponse
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.shortcuts import get_object_or_404, render,redirect
from . import forms,models
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required,user_passes_test
from django.conf import settings
from django.urls import reverse

def home_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')
    if 's' in request.GET:
        s=request.GET['s']
        data=models.Subject.objects.filter(subject_name__icontains=s)
    else:
        data=models.Subject.objects.all()
    paginator=Paginator(data,3)
    page=request.GET.get('page')
    try:
        data=paginator.page(page)
    except PageNotAnInteger:
        data=paginator.page(1)
    except EmptyPage:
        data=paginator.page(paginator.num_pages)
    return render(request,'management/index.html',{'data':data,'page':page})
# def home_view(request):
#     if request.user.is_authenticated:
#         return HttpResponseRedirect('afterlogin')
#     data=models.Subject.objects.all()
#     paginator=Paginator(data,3)
#     page=request.GET.get('page')
#     try:
#         data=paginator.page(page)
#     except PageNotAnInteger:
#         data=paginator.page(1)
#     except EmptyPage:
#         data=paginator.page(paginator.num_pages)

#     return render(request,'management/index.html',{'data':data,'page':page})

def detail_page(request,subect_id):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')
    obj=get_object_or_404(models.Subject,pk=subect_id)
    return render(request,'management/detail.html',{'obj':obj})

def adminclick_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')
    return render(request,'management/adminclick.html')

def teacherclick_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')
    return render(request,'management/teacherclick.html')


def studentclick_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')
    return render(request,'management/studentclick.html')

def admin_signup_view(request):
    form=forms.AdminSigupForm()
    if request.method=='POST':
        form=forms.AdminSigupForm(request.POST)
        if form.is_valid():
            user=form.save()
            user.set_password(user.password)
            user.save()


            my_admin_group = Group.objects.get_or_create(name='ADMIN')
            my_admin_group[0].user_set.add(user)

            return HttpResponseRedirect('adminlogin')
    return render(request,'management/adminsignup.html',{'form':form})

def student_signup_view(request):
    form1=forms.StudentUserForm()
    form2=forms.StudentExtraForm()
    mydict={'form1':form1,'form2':form2}
    if request.method=='POST':
        form1=forms.StudentUserForm(request.POST)
        form2=forms.StudentExtraForm(request.POST)
        if form1.is_valid() and form2.is_valid():
            user=form1.save()
            user.set_password(user.password)
            user.save()
            f2=form2.save(commit=False)
            f2.user=user
            user2=f2.save()

            my_student_group = Group.objects.get_or_create(name='STUDENT')
            my_student_group[0].user_set.add(user)

        return HttpResponseRedirect('studentlogin')
    return render(request,'management/studentsignup.html',context=mydict)

def teacher_signup_view(request):
    form1=forms.TeacherUserForm()
    form2=forms.TeacherExtraForm()
    mydict={'form1':form1,'form2':form2}
    if request.method=='POST':
        form1=forms.TeacherUserForm(request.POST)
        form2=forms.TeacherExtraForm(request.POST)
        if form1.is_valid() and form2.is_valid():
            user=form1.save()
            user.set_password(user.password)
            user.save()
            f2=form2.save(commit=False)
            f2.user=user
            user2=f2.save()

            my_teacher_group = Group.objects.get_or_create(name='TEACHER')
            my_teacher_group[0].user_set.add(user)

        return HttpResponseRedirect('teacherlogin')
    return render(request,'management/teachersignup.html',context=mydict)


def is_admin(user):
    return user.groups.filter(name='ADMIN').exists()
def is_teacher(user):
    return user.groups.filter(name='TEACHER').exists()
def is_student(user):
    return user.groups.filter(name='STUDENT').exists()


def afterlogin_view(request):
    if is_admin(request.user):
        
        return HttpResponseRedirect('admin-dashboard')
    elif is_teacher(request.user):
        accountapproval=models.Teacher.objects.all().filter(user_id=request.user.id,status=True)
        if accountapproval:
            
            return HttpResponseRedirect('teacher-dashboard')
        else:
            return render(request,'management/teacher_wait_for_approval.html')
    elif is_student(request.user):
        accountapproval=models.Student.objects.all().filter(user_id=request.user.id,status=True)
        if accountapproval:
            return HttpResponseRedirect('student-dashboard')
        else:
            return render(request,'management/student_wait_for_approval.html')


@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def admin_dashboard_view(request):
    teachercount=models.Teacher.objects.all().filter(status=True).count()
    pendingteachercount=models.Teacher.objects.all().filter(status=False).count()

    studentcount=models.Student.objects.all().filter(status=True).count()
    pendingstudentcount=models.Student.objects.all().filter(status=False).count()

    notice=models.Notice.objects.all()

    mydict={
        'teachercount':teachercount,
        'pendingteachercount':pendingteachercount,

        'studentcount':studentcount,
        'pendingstudentcount':pendingstudentcount,

        'notice':notice,
    }
    return render(request,'management/admin_dashboard.html',context=mydict)



@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def admin_teacher_view(request):
    return render(request,'management/admin_teacher.html')

@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def admin_add_teacher_view(request):
    form1=forms.TeacherUserForm()
    form2=forms.TeacherExtraForm()
    mydict={'form1':form1,'form2':form2}
    if request.method=='POST':
        form1=forms.TeacherUserForm(request.POST)
        form2=forms.TeacherExtraForm(request.POST)
        if form1.is_valid() and form2.is_valid():
            user=form1.save()
            user.set_password(user.password)
            user.save()

            f2=form2.save(commit=False)
            f2.user=user
            f2.status=True
            f2.save()

            my_teacher_group = Group.objects.get_or_create(name='TEACHER')
            my_teacher_group[0].user_set.add(user)

        return HttpResponseRedirect('admin-teacher')
    return render(request,'management/admin_add_teacher.html',context=mydict)

@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def admin_view_teacher_view(request):
    teachers=models.Teacher.objects.all().filter(status=True)
    return render(request,'management/admin_view_teacher.html',{'teachers':teachers})

@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def admin_approve_teacher_view(request):
    teachers=models.Teacher.objects.all().filter(status=False)
    return render(request,'management/admin_approve_teacher.html',{'teachers':teachers})

@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def approve_teacher_view(request,pk):
    teacher=models.Teacher.objects.get(id=pk)
    teacher.status=True
    teacher.save()
    # return redirect(reverse('admin-approve-teacher'))
    # return HttpResponseRedirect(reverse('admin-approve-teacher'))
    return render(request,'management/updatemessage.html')


@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def delete_teacher_view(request,pk):
    teacher=models.Teacher.objects.get(id=pk)
    user=models.User.objects.get(id=teacher.user_id)
    user.delete()
    teacher.delete()
    # return redirect('admin-approve-teacher')
    return render(request,'management/admin_approve_teacher.html')

@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def delete_teacher_from_school_view(request,pk):
    teacher=models.Teacher.objects.get(id=pk)
    user=models.User.objects.get(id=teacher.user_id)
    user.delete()
    teacher.delete()
    # return redirect('admin-view-teacher')
    return render(request,'management/admin_view_teacher.html')

@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def update_teacher_view(request,pk):
    teacher=models.Teacher.objects.get(id=pk)
    user=models.User.objects.get(id=teacher.user_id)

    form1=forms.TeacherUserForm(instance=user)
    form2=forms.TeacherExtraForm(instance=teacher)
    mydict={'form1':form1,'form2':form2}

    if request.method=='POST':
        form1=forms.TeacherUserForm(request.POST,instance=user)
        form2=forms.TeacherExtraForm(request.POST,instance=teacher)
        print(form1)
        if form1.is_valid() and form2.is_valid():
            user=form1.save()
            user.set_password(user.password)
            user.save()
            f2=form2.save(commit=False)
            f2.status=True
            f2.save()
            # return HttpResponseRedirect('admin-view-teacher')
        return render(request,'management/updatemessage.html')
    return render(request,'management/admin_update_teacher.html',context=mydict)



@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def admin_student_view(request):
    return render(request,'management/admin_student.html')

@login_required(login_url='adminlogin')

management/templates/management/admin_approve_student.html
{% extends 'management/adminbase.html' %}
{% block title %}Fresh Start{% endblock title %}
{% block body %}

<head>

  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style>
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
    
  </style>

</head>



  <div class="row">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h6 class="panel-title">Students</h6>

      </div>

      <table class="table table-hover" id="dev-table">
        <thead>

          <tr>
            <th>Name</th>
            <th>Joining Date</th>
            <th>Mobile</th>
            <th>Approve</th>
            <th>Delete</th>
          </tr>
        </thead>
        {% for s in students %}
        <tr>
          <td>{{s.get_name}}</td>
          <td>{{s.joindate}}</td>
          <td>{{s.mobile}}</td>
          <td><a class="btn btn-primary btn-xs" href="{% url 'management:approve-student' s.id  %}"><span class="glyphicon glyphicon-ok"></span></a></td>
          <td><a class="btn btn-danger btn-xs" href="{% url 'management:delete-student' s.id  %}"><span class="glyphicon glyphicon-trash"></span></a></td>
        </tr>

        {% endfor %}
      </table>
    </div>


  </div>




{% endblock body %}

management/templates/management/admin_dashboard_cards.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Fresh Start{% endblock title %}
{% block content %}
  <style>
    a:link {
      text-decoration: none;
    }

    .order-card {
      color: #fff;
    }

    .bg-c-blue {
      background: linear-gradient(45deg, #4099ff, #73b4ff);
    }

    .bg-c-green {
      background: linear-gradient(45deg, #2ed8b6, #59e0c5);
    }

    .bg-c-yellow {
      background: linear-gradient(45deg, #FFB64D, #ffcb80);
    }

    .bg-c-pink {
      background: linear-gradient(45deg, #FF5370, #ff869a);
    }


    .card {
      border-radius: 5px;
      -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
      box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
      border: none;
      margin-bottom: 30px;
      -webkit-transition: all 0.3s ease-in-out;
      transition: all 0.3s ease-in-out;
    }

    .card .card-block {
      padding: 25px;
    }

    .order-card i {
      font-size: 26px;
    }

    .f-left {
      float: left;
    }

    .f-right {
      float: right;
    }
  </style>
</head>

<body>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-xl-6">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20">Total Teacher</h6>
            <h2 class="text-right"><i class="fas fa-chalkboard-teacher f-left"></i><span>{{teachercount}}</span></h2>
            <p class="m-b-0">Pending Teacher<span class="f-right">{{pendingteachercount}}</span></p>
          </div>
        </div>
      </div>

      <div class="col-md-6 col-xl-6">
        <div class="card bg-c-green order-card">
          <div class="card-block">
            <h6 class="m-b-20">Total Student</h6>
            <h2 class="text-right"><i class="fas fa-user-graduate f-left"></i><span>{{studentcount}}</span></h2>
            <p class="m-b-0">Pending Students<span class="f-right">{{pendingstudentcount}}</span></p>
          </div>
        </div>
      </div>

    </div>
  </div>


  

  <script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
  <script type="text/javascript">

  </script>
{% endblock content %}

management/templates/management/admin_update_student.html
{% extends 'management/adminbase.html' %}

{% load widget_tweaks %}

{% block title %}Fresh Start{% endblock title %}

{% block body %}

<head>
  <style>
    a:link {
      text-decoration: none;
    }

    .note {
      text-align: center;
      height: 80px;
      background: -webkit-linear-gradient(left, #0072ff, #8811c5);
      color: #fff;
      font-weight: bold;
      line-height: 80px;
    }

    .form-content {
      padding: 5%;
      border: 1px solid #ced4da;
      margin-bottom: 2%;
    }

    .form-control {
      border-radius: 1.5rem;
    }

    .btnSubmit {
      border: none;
      border-radius: 1.5rem;
      padding: 1%;
      width: 20%;
      cursor: pointer;
      background: #0062cc;
      color: #fff;
    }
  </style>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</head>


<form method="post">
  {% csrf_token %}
  <div class="container register-form">
    <div class="form">
      <div class="note">
        <p>Update Student Details</p>
      </div>

      <div class="form-content">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              {% render_field form1.first_name class="form-control" placeholder="First Name" %}
            </div>
            <div class="form-group">
              {% render_field form1.username class="form-control" placeholder="Username" %}
            </div>
            <div class="form-group">
              {% render_field form2.mobile class="form-control" placeholder="Mobile" %}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              {% render_field form1.last_name class="form-control" placeholder="Last Name" %}
            </div>
            <div class="form-group">
              {% render_field form1.password class="form-control" placeholder="Password" %}
            </div>
          </div>
        </div>
        <button type="submit" class="btnSubmit">Submit</button>
      </div>
    </div>
  </div>

</form>


{% endblock body %}

management/templates/management/adminclick.html
{% extends 'management/homebase.html' %}



{% block title %}Fresh Start{% endblock title %}
{% block content %}

<br>
<br>
{% include "management/navbar.html" %}
<div class="container">
  <br><br><br><br><br>
<center>
<div class="jumbotron" style="margin-bottom:0px;">
  <h1 class="display-4">Hello, Admin</h1>
  <p class="lead">Welcome to Online Learning Platform.</p>
  <hr class="my-4">
  <p>You can access various features after Login/SignUp.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="adminsignup" role="button">SignUp</a>
    <a class="btn btn-primary btn-lg" href="adminlogin" role="button">Login</a>
  </p>
</div>
</center>

</div>
{% include "management/footer.html" %}
{% endblock content %}

management/templates/management/studentbase.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>Fresh Start</title>

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    body {
      margin: 0;
      padding: 0;
      font-family: "Roboto", sans-serif;
    }

    header {
      position: fixed;
      background:#f8ac07;
      padding: 20px;
      width: 100%;

      z-index: 1;
    }

    .left_area h3 {
      color: rgb(8, 8, 8);
      margin: 0px;
      text-transform: uppercase;
      font-size: 22px;
      font-weight: 900;
    }

    .left_area span {
      color: black;
    }

    .logout_btn {
      padding: 5px;
      background: #0a0a0a;
      text-decoration: none;
      float: right;
      margin-top: -30px;
      margin-right: 40px;
      border-radius: 2px;
      font-size: 15px;
      font-weight: 600;
      color:#f8f4f4;
      transition: 0.5s;
      transition-property: background;
    }

    .logout_btn:hover {
      background:#d6f3fa;
    }

    .sidebar {
      background: #f5c117;
      margin-top: 70px;
      padding-top: 30px;
      position: fixed;
      left: 0;
      width: 250px;
      height: 100%;
      transition: 0.5s;
      transition-property: left;
    }

    .sidebar .profile_image {
      width: 100px;
      height: 100px;
      border-radius: 100px;
      margin-bottom: 10px;
    }

    .sidebar h4 {
      color: rgb(12, 12, 12);
      margin-top: 0;
      margin-bottom: 20px;
    }

    .sidebar a {
      color:black;
      display: block;
      width: 100%;
      line-height: 60px;
      text-decoration: none;
      padding-left: 40px;
      box-sizing: border-box;
      transition: 0.5s;
      transition-property: background;
    }

    .sidebar a:hover {
      background: #d6f3fa;
    }

    .sidebar i {
      padding-right: 10px;
    }

    label #sidebar_btn {
      z-index: 1;
      color: rgb(10, 10, 10);
      position: fixed;
      cursor: pointer;
      left: 300px;
      font-size: 20px;
      margin: 5px 0;
      transition: 0.5s;
      transition-property: color;
    }

    label #sidebar_btn:hover {
      color: #030607;
    }

    #check:checked~.sidebar {
      left: -190px;
    }

    #check:checked~.sidebar a span {
      display: none;
    }

    #check:checked~.sidebar a {
      font-size: 20px;
      margin-left: 170px;
      width: 80px;
    }

    .content {
      margin-left: 250px;
      background: url(background.png) no-repeat;
      background-position: center;
      background-size: cover;
      height: 100vh;
      transition: 0.5s;
    }

    #check:checked~.content {
      margin-left: 60px;
    }

    #check {
      display: none;
    }
  </style>


  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">


</head>

<body>

  <input type="checkbox" id="check">
  
  <header>
    <label for="check">
      <i class="fas fa-bars" id="sidebar_btn"></i>
    </label>
    <div class="left_area">
      <h3>Fresh Start</h3>
    </div>
    <div class="right_area">
      <a href="/logout" class="logout_btn">Logout</a>
    </div>
  </header>
  
  <div class="sidebar">
    <center>

      <img src="{% static "images/student1.png" %}" class="profile_image" alt="">
      <h4>{{request.user.first_name}}</h4>

    </center>

    <a href="/student-dashboard"><i class="fas fa-desktop"></i><span>Dashboard</span></a>
    <a href="/student_joinmeeting"><i class="far fa-handshake"></i><span>Join the Meeting</span></a>
    <a style="color:rgb(7, 7, 7)" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <i class="fab fa-chrome"></i><span>Browsing Material</span></a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a style="color:black" class="dropdown-item" href="{% url 'studymaterial:youtube' %}">Youtube</a></li>
        <li><a style="color:black" class="dropdown-item" href="{% url 'studymaterial:wikipedias' %}">Wikipedia</a></li>
        <li><a style="color:black" class="dropdown-item" href="{% url 'studymaterial:dictionary' %}">Dictionary</a></li>
        <li><a style="color:black" class="dropdown-item" href="{% url 'studymaterial:books' %}">BOOKS</a></li>
      </ul>


  </div>
  
  <div class="content">
    <br><br><br><br><br>
    {% block content %}

    {% endblock content %}


    <br><br><br>
    {% include "management/footer.html" %}
  </div>
  
</body>

</html>